name: C/C++ AppImage

on:
  push:
    branches:
    - master
  pull_request:
    branches: 
    - master

jobs:
  build-appimage:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y qt5-default qtdeclarative5-dev cmake
      - name: configure
        run: qmake
      - name: build
        run: make
      - name: create directory
        run: mkdir -p AppDir/usr/bin
      - name: copy binary
        run: mv selectdefaultapplication AppDir/usr/bin/
      - name: Build AppImage
        uses: AppImageCrafters/build-appimage-action@master
        env:
          UPDATE_INFO: gh-releases-zsync|magnus-ISU|selectdefaultapplication|latest|*x86_64.AppImage.zsync
        with:
          recipe: AppImageBuilder.yml
      - uses: actions/upload-artifact@v2
        with:
          name: AppImage
